# **Self Define Supervised Learning Problem**

Please use this notebook to work on your own supervised learning problem, if you choose to identify one yourself.

Please follow the guidance below to provide this minimum required information for the lab.

**About the data set**

In the text box below, please describe the problem that you have selected.

**Import libraries**

In [200]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Add all needed libraries to work on your data set
#import random as rnd
import random as rnd
# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Acquired data

Use pandas to read in the data set.

Note: Make sure that the data set's csv file is saved into SupervisedLearning/Custom directory.

In [202]:
train_df = pd.read_csv('ReinforcementLearning/SupervisedLearning/Custom/healthy_lifestyle_city_2021.csv')

In [203]:
train_df

,City,Rank,Sunshine hours(City),Cost of a bottle of water(City),Obesity levels(Country),Life expectancy(years) (Country),Pollution(Index score) (City),Annual avg. hours worked,Happiness levels(Country),Outdoor activities(City),Number of take out places(City),Cost of a monthly gym membership(City)
0,Amsterdam,1,1858,£1.92,20.40%,81.2,30.93,1434,7.44,422,1048,£34.90
1,Sydney,2,2636,£1.48,29.00%,82.1,26.86,1712,7.22,406,1103,£41.66
2,Vienna,3,1884,£1.94,20.10%,81.0,17.33,1501,7.29,132,1008,£25.74
3,Stockholm,4,1821,£1.72,20.60%,81.8,19.63,1452,7.35,129,598,£37.31
4,Copenhagen,5,1630,£2.19,19.70%,79.8,21.24,1380,7.64,154,523,£32.53
5,Helsinki,6,1662,£1.60,22.20%,80.4,13.08,1540,7.80,113,309,£35.23
6,Fukuoka,7,2769,£0.78,4.30%,83.2,-,1644,5.87,35,539,£55.87
7,Berlin,8,1626,£1.55,22.30%,80.6,39.41,1386,7.07,254,1729,£26.11
8,Barcelona,9,2591,£1.19,23.80%,82.2,65.19,1686,6.40,585,2344,£37.80
9,Vancouver,10,1938,£1.08,29.40%,81.7,24.26,1670,7.23,218,788,£31.04
10,Melbourne,11,2363,£1.57,29.00%,82.1,25.90,1712,7.22,243,813,£36.89
11,Beijing,12,2671,£0.26,6.20%,75.4,85.43,-,5.12,223,261,£38.62
12,Bangkok,13,2624,£0.22,10.00%,74.1,76.64,-,5.99,377,1796,£50.03
13,Buenos Aires,14,2525,£0.57,28.30%,75.9,52.64,-,5.97,246,1435,£22.45
14,Toronto,15,2066,£1.09,29.40%,81.7,37.83,1670,7.23,174,1656,£32.64
15,Madrid,16,2769,£1.30,23.80%,82.2,52.68,1686,6.40,216,2491,£34.54
16,Jakarta,17,2983,£0.21,6.90%,68.5,84.39,-,5.28,114,833,£29.94
17,Seoul,18,2066,£0.59,4.70%,81.3,57.82,1967,5.87,144,389,£43.03
18,Frankfurt,19,1662,£1.95,22.30%,80.6,37.78,1386,7.07,23,551,£39.01
19,Geneva,20,-,£2.62,19.50%,82.6,27.25,1557,7.56,44,444,£70.00
20,Tel Aviv,21,3311,£1.63,26.10%,81.9,47.28,1898,7.12,139,420,£58.31
21,Istanbul,22,2218,£0.15,32.10%,74.7,69.49,1832,5.13,419,934,£16.97
22,Cairo,23,3542,£0.16,32.00%,70.7,91.74,-,4.15,323,250,£23.25
23,Taipei,24,1405,£0.57,6.20%,75.4,49.32,-,5.12,134,717,£34.76
24,Los Angeles,25,3254,£1.52,36.20%,78.8,66.07,1779,6.94,223,1439,£32.00
25,Mumbai,26,2584,£0.15,3.90%,67.3,82.84,-,3.57,187,1183,£19.54
26,Boston,27,2634,£1.39,36.20%,78.8,27.03,1779,6.94,88,588,£46.27
27,Dublin,28,1453,£1.40,25.30%,80.5,40.07,1772,7.09,159,659,£37.35
28,Tokyo,29,1877,£0.76,4.30%,83.2,42.84,1644,5.87,387,5802,£70.82
29,Chicago,30,2508,£1.20,36.20%,78.8,43.33,1779,6.94,171,1320,£41.14
30,Hong Kong,31,1836,£0.75,6.20%,75.4,67.46,-,5.51,277,1257,£57.95
31,Shanghai,32,1776,£0.29,6.20%,75.4,77.40,-,5.12,108,346,£44.68
32,Brussels,33,1546,£2.11,22.10%,80.4,62.67,1583,6.86,55,988,£25.34
33,San Francisco,34,3062,£1.60,36.20%,78.8,47.36,1779,6.94,242,1031,£65.13
34,Paris,35,1662,£1.95,21.60%,81.8,65.10,1505,6.66,331,4363,£35.93
35,Sao Paulo,36,2003,£0.44,22.10%,73.9,79.78,-,6.37,158,3355,£16.07
36,Zurich,37,1566,£3.20,19.50%,82.6,17.31,1557,7.56,69,538,£73.11
37,London,38,1633,£1.16,27.80%,80.4,58.91,1538,7.16,433,6417,£42.71
38,Johannesburg,39,3124,£0.59,28.30%,56.3,61.83,-,4.81,194,492,£24.28
39,Milan,40,1915,£1.15,19.90%,82.7,67.19,1718,6.38,110,2396,£53.49
40,"Washington, D.C.",41,2528,£1.45,36.20%,78.8,39.18,1779,6.94,83,744,£65.99
41,New York,42,2535,£1.32,36.20%,78.8,57.36,1779,6.94,359,3081,£64.66
42,Moscow,43,1901,£0.41,23.10%,69.5,57.63,1965,5.54,322,3206,£31.40
43,Mexico City,44,2555,£0.45,28.90%,76.4,82.78,2137,6.46,192,1313,£41.99

# Inspect data

Create coding blocks below to inspect the data.

In [204]:
#TODO: Write code to inspect the shape of the data frame
train_df.shape

(44, 12)

In [205]:
#TODO: Write code to display information about the data frame
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   City                                    44 non-null     object
 1   Rank                                    44 non-null     int64
 2   Sunshine hours(City)                    44 non-null     object
 3   Cost of a bottle of water(City)         44 non-null     object
 4   Obesity levels(Country)                 44 non-null     object
 5   Life expectancy(years) (Country)        44 non-null     float64
 6   Pollution(Index score) (City)           44 non-null     object
 7   Annual avg. hours worked                44 non-null     object
 8   Happiness levels(Country)               44 non-null     float64
 9   Outdoor activities(City)                44 non-null     int64
 10  Number of take out places(City)         44 non-null     int64
 11  Cost of a monthly gym membership(City)  44 non-null     object
dtypes: float64(2), int64(3), object(7)
memory usage: 4.2+ KB

In [206]:
#TODO: Write code to display statistics about the data frame
train_df.describe()

,Rank,Life expectancy(years) (Country),Happiness levels(Country),Outdoor activities(City),Number of take out places(City)
count,44.000000,44.00000,44.000000,44.000000,44.000000
mean,22.500000,78.17500,6.435000,213.977273,1443.113636
std,12.845233,5.30437,0.991202,127.190297,1388.803270
min,1.000000,56.30000,3.570000,23.000000,250.000000
25%,11.750000,75.40000,5.870000,125.250000,548.000000
50%,22.500000,80.40000,6.900000,189.500000,998.000000
75%,33.250000,81.80000,7.175000,288.250000,1674.250000
max,44.000000,83.20000,7.800000,585.000000,6417.000000

# Clean data

Create coding blocks below to clean and prepare the data. At the minimum, make sure to get rid of rows with missing values, and replace any categorical variables.

In [207]:
# 1 gpd = 1.32 US dollars

In [208]:
train_df.shape[0]

44

In [209]:
float(train_df['Cost of a bottle of water(City)'][i][1:]) * 1.32

1.0296

In [210]:
# Taking Care of Missing Values

In [211]:
train_df[train_df['Sunshine hours(City)'] == '-'] = '0'
train_df[train_df['Annual avg. hours worked'] == '-'] = '0'
train_df[train_df['Pollution(Index score) (City)'] == '-'] = '0'

In [212]:
train_df.loc[19]['Sunshine hours(City)']

'0'

In [213]:
train_df = train_df[train_df['City'] != '0']

In [214]:
train_df

,City,Rank,Sunshine hours(City),Cost of a bottle of water(City),Obesity levels(Country),Life expectancy(years) (Country),Pollution(Index score) (City),Annual avg. hours worked,Happiness levels(Country),Outdoor activities(City),Number of take out places(City),Cost of a monthly gym membership(City)
0,Amsterdam,1,1858,£1.92,20.40%,81.2,30.93,1434,7.44,422,1048,£34.90
1,Sydney,2,2636,£1.48,29.00%,82.1,26.86,1712,7.22,406,1103,£41.66
2,Vienna,3,1884,£1.94,20.10%,81.0,17.33,1501,7.29,132,1008,£25.74
3,Stockholm,4,1821,£1.72,20.60%,81.8,19.63,1452,7.35,129,598,£37.31
4,Copenhagen,5,1630,£2.19,19.70%,79.8,21.24,1380,7.64,154,523,£32.53
5,Helsinki,6,1662,£1.60,22.20%,80.4,13.08,1540,7.8,113,309,£35.23
7,Berlin,8,1626,£1.55,22.30%,80.6,39.41,1386,7.07,254,1729,£26.11
8,Barcelona,9,2591,£1.19,23.80%,82.2,65.19,1686,6.4,585,2344,£37.80
9,Vancouver,10,1938,£1.08,29.40%,81.7,24.26,1670,7.23,218,788,£31.04
10,Melbourne,11,2363,£1.57,29.00%,82.1,25.90,1712,7.22,243,813,£36.89
14,Toronto,15,2066,£1.09,29.40%,81.7,37.83,1670,7.23,174,1656,£32.64
15,Madrid,16,2769,£1.30,23.80%,82.2,52.68,1686,6.4,216,2491,£34.54
17,Seoul,18,2066,£0.59,4.70%,81.3,57.82,1967,5.87,144,389,£43.03
18,Frankfurt,19,1662,£1.95,22.30%,80.6,37.78,1386,7.07,23,551,£39.01
20,Tel Aviv,21,3311,£1.63,26.10%,81.9,47.28,1898,7.12,139,420,£58.31
21,Istanbul,22,2218,£0.15,32.10%,74.7,69.49,1832,5.13,419,934,£16.97
24,Los Angeles,25,3254,£1.52,36.20%,78.8,66.07,1779,6.94,223,1439,£32.00
26,Boston,27,2634,£1.39,36.20%,78.8,27.03,1779,6.94,88,588,£46.27
27,Dublin,28,1453,£1.40,25.30%,80.5,40.07,1772,7.09,159,659,£37.35
28,Tokyo,29,1877,£0.76,4.30%,83.2,42.84,1644,5.87,387,5802,£70.82
29,Chicago,30,2508,£1.20,36.20%,78.8,43.33,1779,6.94,171,1320,£41.14
32,Brussels,33,1546,£2.11,22.10%,80.4,62.67,1583,6.86,55,988,£25.34
33,San Francisco,34,3062,£1.60,36.20%,78.8,47.36,1779,6.94,242,1031,£65.13
34,Paris,35,1662,£1.95,21.60%,81.8,65.10,1505,6.66,331,4363,£35.93
36,Zurich,37,1566,£3.20,19.50%,82.6,17.31,1557,7.56,69,538,£73.11
37,London,38,1633,£1.16,27.80%,80.4,58.91,1538,7.16,433,6417,£42.71
39,Milan,40,1915,£1.15,19.90%,82.7,67.19,1718,6.38,110,2396,£53.49
40,"Washington, D.C.",41,2528,£1.45,36.20%,78.8,39.18,1779,6.94,83,744,£65.99
41,New York,42,2535,£1.32,36.20%,78.8,57.36,1779,6.94,359,3081,£64.66
42,Moscow,43,1901,£0.41,23.10%,69.5,57.63,1965,5.54,322,3206,£31.40
43,Mexico City,44,2555,£0.45,28.90%,76.4,82.78,2137,6.46,192,1313,£41.99

In [215]:
train_df = train_df.reset_index()

In [216]:
train_df

,index,City,Rank,Sunshine hours(City),Cost of a bottle of water(City),Obesity levels(Country),Life expectancy(years) (Country),Pollution(Index score) (City),Annual avg. hours worked,Happiness levels(Country),Outdoor activities(City),Number of take out places(City),Cost of a monthly gym membership(City)
0,0,Amsterdam,1,1858,£1.92,20.40%,81.2,30.93,1434,7.44,422,1048,£34.90
1,1,Sydney,2,2636,£1.48,29.00%,82.1,26.86,1712,7.22,406,1103,£41.66
2,2,Vienna,3,1884,£1.94,20.10%,81.0,17.33,1501,7.29,132,1008,£25.74
3,3,Stockholm,4,1821,£1.72,20.60%,81.8,19.63,1452,7.35,129,598,£37.31
4,4,Copenhagen,5,1630,£2.19,19.70%,79.8,21.24,1380,7.64,154,523,£32.53
5,5,Helsinki,6,1662,£1.60,22.20%,80.4,13.08,1540,7.8,113,309,£35.23
6,7,Berlin,8,1626,£1.55,22.30%,80.6,39.41,1386,7.07,254,1729,£26.11
7,8,Barcelona,9,2591,£1.19,23.80%,82.2,65.19,1686,6.4,585,2344,£37.80
8,9,Vancouver,10,1938,£1.08,29.40%,81.7,24.26,1670,7.23,218,788,£31.04
9,10,Melbourne,11,2363,£1.57,29.00%,82.1,25.90,1712,7.22,243,813,£36.89
10,14,Toronto,15,2066,£1.09,29.40%,81.7,37.83,1670,7.23,174,1656,£32.64
11,15,Madrid,16,2769,£1.30,23.80%,82.2,52.68,1686,6.4,216,2491,£34.54
12,17,Seoul,18,2066,£0.59,4.70%,81.3,57.82,1967,5.87,144,389,£43.03
13,18,Frankfurt,19,1662,£1.95,22.30%,80.6,37.78,1386,7.07,23,551,£39.01
14,20,Tel Aviv,21,3311,£1.63,26.10%,81.9,47.28,1898,7.12,139,420,£58.31
15,21,Istanbul,22,2218,£0.15,32.10%,74.7,69.49,1832,5.13,419,934,£16.97
16,24,Los Angeles,25,3254,£1.52,36.20%,78.8,66.07,1779,6.94,223,1439,£32.00
17,26,Boston,27,2634,£1.39,36.20%,78.8,27.03,1779,6.94,88,588,£46.27
18,27,Dublin,28,1453,£1.40,25.30%,80.5,40.07,1772,7.09,159,659,£37.35
19,28,Tokyo,29,1877,£0.76,4.30%,83.2,42.84,1644,5.87,387,5802,£70.82
20,29,Chicago,30,2508,£1.20,36.20%,78.8,43.33,1779,6.94,171,1320,£41.14
21,32,Brussels,33,1546,£2.11,22.10%,80.4,62.67,1583,6.86,55,988,£25.34
22,33,San Francisco,34,3062,£1.60,36.20%,78.8,47.36,1779,6.94,242,1031,£65.13
23,34,Paris,35,1662,£1.95,21.60%,81.8,65.10,1505,6.66,331,4363,£35.93
24,36,Zurich,37,1566,£3.20,19.50%,82.6,17.31,1557,7.56,69,538,£73.11
25,37,London,38,1633,£1.16,27.80%,80.4,58.91,1538,7.16,433,6417,£42.71
26,39,Milan,40,1915,£1.15,19.90%,82.7,67.19,1718,6.38,110,2396,£53.49
27,40,"Washington, D.C.",41,2528,£1.45,36.20%,78.8,39.18,1779,6.94,83,744,£65.99
28,41,New York,42,2535,£1.32,36.20%,78.8,57.36,1779,6.94,359,3081,£64.66
29,42,Moscow,43,1901,£0.41,23.10%,69.5,57.63,1965,5.54,322,3206,£31.40
30,43,Mexico City,44,2555,£0.45,28.90%,76.4,82.78,2137,6.46,192,1313,£41.99

In [217]:
# Replacing Categorical Variables

In [218]:
for i in range(train_df.shape[0]):
    train_df['Cost of a bottle of water(City)'][i] = float(train_df['Cost of a bottle of water(City)'][i][1:]) * 1.32
    train_df['Sunshine hours(City)'][i] = float(train_df['Sunshine hours(City)'][i])
    train_df['Cost of a monthly gym membership(City)'][i] = float(train_df['Cost of a monthly gym membership(City)'][i][1:]) * 1.32

/tmp/ipykernel_114/3966699313.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['Cost of a bottle of water(City)'][i] = float(train_df['Cost of a bottle of water(City)'][i][1:]) * 1.32
/tmp/ipykernel_114/3966699313.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['Sunshine hours(City)'][i] = float(train_df['Sunshine hours(City)'][i])
/tmp/ipykernel_114/3966699313.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['Cost of a monthly gym membership(City)'][i] = float(train_df['Cost of a monthly gym membership(City)'][i][1:]) * 1.32

In [220]:
train_df

,index,City,Rank,Sunshine hours(City),Cost of a bottle of water(City),Obesity levels(Country),Life expectancy(years) (Country),Pollution(Index score) (City),Annual avg. hours worked,Happiness levels(Country),Outdoor activities(City),Number of take out places(City),Cost of a monthly gym membership(City)
0,0,Amsterdam,1,1858.0,2.5344,20.40%,81.2,30.93,1434,7.44,422,1048,46.068
1,1,Sydney,2,2636.0,1.9536,29.00%,82.1,26.86,1712,7.22,406,1103,54.9912
2,2,Vienna,3,1884.0,2.5608,20.10%,81.0,17.33,1501,7.29,132,1008,33.9768
3,3,Stockholm,4,1821.0,2.2704,20.60%,81.8,19.63,1452,7.35,129,598,49.2492
4,4,Copenhagen,5,1630.0,2.8908,19.70%,79.8,21.24,1380,7.64,154,523,42.9396
5,5,Helsinki,6,1662.0,2.112,22.20%,80.4,13.08,1540,7.8,113,309,46.5036
6,7,Berlin,8,1626.0,2.046,22.30%,80.6,39.41,1386,7.07,254,1729,34.4652
7,8,Barcelona,9,2591.0,1.5708,23.80%,82.2,65.19,1686,6.4,585,2344,49.896
8,9,Vancouver,10,1938.0,1.4256,29.40%,81.7,24.26,1670,7.23,218,788,40.9728
9,10,Melbourne,11,2363.0,2.0724,29.00%,82.1,25.90,1712,7.22,243,813,48.6948
10,14,Toronto,15,2066.0,1.4388,29.40%,81.7,37.83,1670,7.23,174,1656,43.0848
11,15,Madrid,16,2769.0,1.716,23.80%,82.2,52.68,1686,6.4,216,2491,45.5928
12,17,Seoul,18,2066.0,0.7788,4.70%,81.3,57.82,1967,5.87,144,389,56.7996
13,18,Frankfurt,19,1662.0,2.574,22.30%,80.6,37.78,1386,7.07,23,551,51.4932
14,20,Tel Aviv,21,3311.0,2.1516,26.10%,81.9,47.28,1898,7.12,139,420,76.9692
15,21,Istanbul,22,2218.0,0.198,32.10%,74.7,69.49,1832,5.13,419,934,22.4004
16,24,Los Angeles,25,3254.0,2.0064,36.20%,78.8,66.07,1779,6.94,223,1439,42.24
17,26,Boston,27,2634.0,1.8348,36.20%,78.8,27.03,1779,6.94,88,588,61.0764
18,27,Dublin,28,1453.0,1.848,25.30%,80.5,40.07,1772,7.09,159,659,49.302
19,28,Tokyo,29,1877.0,1.0032,4.30%,83.2,42.84,1644,5.87,387,5802,93.4824
20,29,Chicago,30,2508.0,1.584,36.20%,78.8,43.33,1779,6.94,171,1320,54.3048
21,32,Brussels,33,1546.0,2.7852,22.10%,80.4,62.67,1583,6.86,55,988,33.4488
22,33,San Francisco,34,3062.0,2.112,36.20%,78.8,47.36,1779,6.94,242,1031,85.9716
23,34,Paris,35,1662.0,2.574,21.60%,81.8,65.10,1505,6.66,331,4363,47.4276
24,36,Zurich,37,1566.0,4.224,19.50%,82.6,17.31,1557,7.56,69,538,96.5052
25,37,London,38,1633.0,1.5312,27.80%,80.4,58.91,1538,7.16,433,6417,56.3772
26,39,Milan,40,1915.0,1.518,19.90%,82.7,67.19,1718,6.38,110,2396,70.6068
27,40,"Washington, D.C.",41,2528.0,1.914,36.20%,78.8,39.18,1779,6.94,83,744,87.1068
28,41,New York,42,2535.0,1.7424,36.20%,78.8,57.36,1779,6.94,359,3081,85.3512
29,42,Moscow,43,1901.0,0.5412,23.10%,69.5,57.63,1965,5.54,322,3206,41.448
30,43,Mexico City,44,2555.0,0.594,28.90%,76.4,82.78,2137,6.46,192,1313,55.4268

In [226]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 13 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   index                                   31 non-null     int64
 1   City                                    31 non-null     object
 2   Rank                                    31 non-null     object
 3   Sunshine hours(City)                    31 non-null     object
 4   Cost of a bottle of water(City)         31 non-null     object
 5   Obesity levels(Country)                 31 non-null     object
 6   Life expectancy(years) (Country)        31 non-null     object
 7   Pollution(Index score) (City)           31 non-null     object
 8   Annual avg. hours worked                31 non-null     object
 9   Happiness levels(Country)               31 non-null     object
 10  Outdoor activities(City)                31 non-null     object
 11  Number of take out places(City)         31 non-null     object
 12  Cost of a monthly gym membership(City)  31 non-null     object
dtypes: int64(1), object(12)
memory usage: 3.3+ KB

Earn Your Wings

Use a decision tree classifier on the cleaned data set to predict y for the given data. Report the accuracy score for 30 runs. Add comments in your code to explain each step that you take in your implementation.

In [242]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [277]:
# defining our features and labels
X = train_df.drop(columns = ['Rank', 'index', 'City', 'Obesity levels(Country)', 'Cost of a bottle of water(City)', 'Life expectancy(years) (Country)', 'Pollution(Index score) (City)', 'Annual avg. hours worked', 'Happiness levels(Country)', 'Outdoor activities(City)', 'Cost of a monthly gym membership(City)'])
y = train_df['Happiness levels(Country)']
# changing the datatype from Object to numeric values
X=X.astype('float')
y=y.astype('int')

# allocation 20% of data to test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
# initializing our model
model = DecisionTreeClassifier()
#training our model
model.fit(X_train, y_train)
predictions = model.predict(X_test)

score = accuracy_score(predictions, y_test)
score

0.5714285714285714

The accuracy score is 57% after 30 runs.